name: NicheScope
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - python=3.9  
  - numpy=1.24.4
  - pandas=2.2.3
  - r-base=4.2.2
  - rpy2=3.5.11
  - seaborn=0.13.2
  - squidpy=1.2.2
  - pip=25.0.1
  - pip:
      - anndata==0.10.8
      - assocplots==0.0.2
      - gseapy==1.1.3
      - matplotlib==3.9.1
      - scanpy==1.10.2
      - scikit-learn==1.6.0
      - scipy==1.13.1
      - gseapy==1.1.3
      - liana==1.5.0
      - adjustText==1.3.0
